import * as o from '../constants'

const Xapo_Plastic_Unverified_GBP = {

  cardID: 'Xapo_Plastic_Unverified_GBP',
  company: o.XAPO,
  cardName: '',
  cardIssuer: o.VISA,
  spendingCurrency: o.USD,
  cardType: o.PLASTIC,
  instantCryptoPayment: true,

  isVerificationRequired: false,
  proofOfAddressRequired: false,
  proofOfIdentityRequired: false,

  monthlyFee: `${o.GBP}0.58*`,
  annualFee: `${o.GBP}7`,

  cardIssuancePrice: `${o.USD}20`,
  cardIssuanceTime: 3,
  cardDeliveryStdPrice: `${o.USD}0`,
  cardDeliveryStdTimeMin: 10,
  cardDeliveryStdTimeMax: 25,
  cardDeliveryExpPrice: `${o.USD}55`,
  cardDeliveryExpTimeMin: 2,
  cardDeliveryExpTimeMax: 7,
  cardReplacementExpPrice: `${o.GBP}35`,
  cardReplacementExpTime: '',
  cardReplacementStdPrice: `${o.GBP}7`,
  cardReplacementStdTime: '',
  pinChange: `${o.GBP}0.6`,

  currencyConversion: '3%',

  connectedWallets: [o.EUR, o.USD, o.GBP, o.BTC, '...150 more'],
  twoFactorsAuth: true,
  cashBack: 0,

  app_IOS: true,
  app_Android: true,
  app_Web: true,

  ATM_Domestic_Widthrawal_Fee: `${o.GBP}1.75`,
  ATM_International_Withdrawal_Fee: `${o.GBP}2.25`,
  ATM_BalanceInquiry_Fee: '',
  ATM_TransactionNumber_24h: 2,
  ATM_TransactionNumber_Month: '56',
  ATM_TransactionNumber_Year: '672*',
  ATM_TransactionNumber_Lifetime: '∞',
  ATM_WithdrawalAmount_Single: `${o.GBP}160`,
  ATM_WithdrawalAmount_24h: `${o.GBP}320`,
  ATM_WithdrawalAmount_Month: `${o.GBP}800*`,
  ATM_WithdrawalAmount_Year: `${o.GBP}800*`,
  ATM_WithdrawalAmount_Lifetime: `${o.GBP}800`,

  Purchases_Total_number_24h: '',
  Purchases_Total_number_month: '',
  Purchases_Total_number_year: '',
  Purchases_Total_number_lifetime: '',
  Purchases_Total_spending_single: `${o.GBP}2000`,
  Purchases_Total_spending_24h: `${o.GBP}2000`,
  Purchases_Total_spending_month: `${o.GBP}2000*`,
  Purchases_Total_spending_year: `${o.GBP}2000*`,
  Purchases_Total_spending_lifetime: `${o.GBP}2000`,
  Purchases_Offline_number_24h: '∞',
  Purchases_Offline_number_year: '∞',
  Purchases_Offline_number_lifetime: '∞',
  Purchases_Offline_spending_single: '∞',
  Purchases_Offline_spending_24h: '∞',
  Purchases_Offline_spending_year: '∞',
  Purchases_Offline_spending_lifetime: '∞',
  Purchases_Online_number_24h: '∞',
  Purchases_Online_number_year: '∞',
  Purchases_Online_number_lifetime: '∞',
  Purchases_Online_spending_single: '∞',
  Purchases_Online_spending_24h: '∞',
  Purchases_Online_spending_year: '∞',
  Purchases_Online_spending_lifetime: '∞',


  WalletLoad_Total_amount: '',
  WalletUnload_Total_amount: '',
  CardLoad_Total_amount: '',
  CarrdUnload_Total_amount: '',


  WalletLoad_Card_available: false,
  WalletLoad_Card_fee: '-',
    WalletLoad_Card_amount_single: '-',
    WalletLoad_Card_amount_24h: '-',
    WalletLoad_Card_amount_lifetime: '-',
    WalletLoad_Card_number_24h: '-',
    WalletLoad_Card_number_month: '-',
    WalletLoad_Card_number_lifetime: '-',

  WalletLoad_BankAccount_available: false,
  WalletLoad_BankAccount_fee: '-',
    WalletLoad_BankAccount_amount_single: '-',
    WalletLoad_BankAccount_amount_24h: '-',
    WalletLoad_BankAccount_amount_lifetime: '-',
    WalletLoad_BankAccount_number_24h: '-',
    WalletLoad_BankAccount_number_month: '-',
    WalletLoad_BankAccount_number_lifetime: '-',

  WalletLoad_Paypal_available: false,
  WalletLoad_Paypal_fee: '-',
    WalletLoad_Paypal_amount_single: `-`,
    WalletLoad_Paypal_amount_24h: `-`,
    WalletLoad_Paypal_amount_lifetime: '-',
    WalletLoad_Paypal_number_24h: '-',
    WalletLoad_Paypal_number_month: '-',
    WalletLoad_Paypal_number_lifetime: '-',

  WalletLoad_Skrill_available: false,
  WalletLoad_Skrill_fee: '-',
    WalletLoad_Skrill_amount_single: `-`,
    WalletLoad_Skrill_amount_24h: `-`,
    WalletLoad_Skrill_amount_lifetime: '-',
    WalletLoad_Skrill_number_24h: '-',
    WalletLoad_Skrill_number_month: '-',
    WalletLoad_Skrill_number_lifetime: '-',

  WalletLoad_Payeer_available: false,
  WalletLoad_Payeer_fee: '-',
    WalletLoad_Payeer_amount_single: `-`,
    WalletLoad_Payeer_amount_24h: `-`,
    WalletLoad_Payeer_amount_lifetime: '-',
    WalletLoad_Payeer_number_24h: '-',
    WalletLoad_Payeer_number_month: '-',
    WalletLoad_Payeer_number_lifetime: '-',

}

export default Xapo_Plastic_Unverified_GBP
